services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command: start --import-realm
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
    ports:
      - "9003:8080"
    networks:
      - keycloak_network
    volumes:
      - ./keycloak-data/realm/realm-export.json:/opt/keycloak/data/import/realm.json

volumes:
  postgres_data:

networks:
  keycloak_network:
    driver: bridge
