server:
  port: 9002

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          registration:
            keycloak:
              client-id: blog-auth-private
              client-secret: k94Hna2SQdRmEhgQqedOBh0LqvMxpFH7
              client-name: fusion-master
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:9002/login/oauth2/code
